### ISSUE TITLE
s3-browser not listing any objects from s3(unable to see any object)

### ISSUE THREAD

**Issue by gopesh1992** [IBM/jupyterlab-s3-browser#52] opened 2021-10-12 18:30 UTC
Hi, I have configured the s3 browser extension as per given instructions in readme but I'm unable to see any object under the bucket icon (once clicked). 

Installed jupyterlab-s3-browser (for jupyter lab 3) following the instructions in the main readme.
Added below environment variables as given in the instructions,

export JUPYTERLAB_S3_ENDPOINT="https://s3.us.cloud-object-storage.appdomain.cloud"
export JUPYTERLAB_S3_ACCESS_KEY_ID="my-access-key-id"
export JUPYTERLAB_S3_SECRET_ACCESS_KEY="secret"  

When click on the bucket icon in the jupyter lab UI (saw no prompt come up to enter aws credentials), but see no objects or any errors

Expected behavior
Expected to be able to see objects in S3 (at least the ones in the AWS account for which the credentials were configured)

Screenshots
![image](https://user-images.githubusercontent.com/28948994/137009899-06c7db87-cfa3-4fb7-9487-fd6714d7be7f.png)

**Comment by reevejd** [comment] 2021-10-18 04:21
Hi @gopesh1992, thanks for reporting the issue. I’m going to try to release a new version of the extension this week after ironing out a few bugs, this will hopefully be one of them. 

If you're eager there's a release candidate available that may already fix the issue, you can try it out with:
```bash
pip install jupyterlab_s3_browser==0.11.0-rc.0 
```

If you're still seeing the issue on the new version please let me know.

**Comment by reevejd** [comment] 2021-11-15 04:39
@mleuthold, thanks for reporting the issue. It's been fixed in `0.11.0-rc.1`.

@gopesh1992 Sorry I didn't read your original message carefully enough. You said:
> saw no prompt come up to enter aws credentials

If you want to set credentials at runtime you should omit the `JUPYTERLAB_S3` environment variables. Or you can set them to your actual credentials instead of the examples I provided. If I've misunderstood and you _are_ using valid credentials for environment variables then I'm not sure what's going on. If you try out `0.11.0-rc.1` are you able to create a new bucket after authenticating?

**Comment by gaolebber** [comment] 2022-03-02 01:21
I'm unable to see any object under the bucket icon 
Steps to reproduce the behavior:
Installed jupyterlab-s3-browser following the instructions in the main readme.
Added below environment variables as given in the instructions,
Configured according to AWS certificate ~ / AWS / credentials configured

export JUPYTERLAB_S3_ENDPOINT="https://s3.us.cloud-object-storage.appdomain.cloud"
export JUPYTERLAB_S3_ACCESS_KEY_ID="xxx"
export JUPYTERLAB_S3_SECRET_ACCESS_KEY="xxx"

When click on the bucket icon in the jupyter lab UI (saw no prompt come up to enter aws credentials), but see no objects or any errors

Expected behavior
Expected to be able to see objects in S3

**Comment by reevejd** [comment] 2022-03-06 16:16
Hi @gaolebber, thanks for reporting the issue. What version of JupyterLab and the extension are you running? You're not seeing the prompt to enter credentials because you've set them through environment variables. If you don't specify the credentials as environment variables, does entering the credentials through the prompt work?

**Comment by gaolebber** [comment] 2022-03-06 17:40
@reevejd 
jupyterlab       : 3.2.1
jupyterlab-s3-browser v0.11.0-rc.1
The problem now is that I specify the configured credentials as environment variables, and there is still no browser information
There is no description in the jupyterhub debug log. Can I get the log description anywhere else

**Comment by gaolebber** [comment] 2022-03-07 06:38
SingleUserLabApp log:189] 404 GET /user/lebber/jupyterlab_s3_browser/files?1646633771191 (lebber@::ffff:172.24.254.210) 20.42ms
    ValueError: "['jupyterlab-spreadsheet@0.4.1', 'jupyterlab-topbar-extension@0.6.0', 'jupyterlab-system-monitor@0.7.0', 'jupyterlab-drawio@0.9.0', '@jupyter-widgets/jupyterlab-manager@3.0.1', '@krassowski/jupyterlab-lsp@3.10.0', 'jupyterlab-s3-browser@0.11.0']" is not a valid npm package

**Comment by reevejd** [comment] 2022-03-07 23:31
@gaolebber thanks for the details. This issue should be fixed in version `0.11.1`, which is now available.

**Comment by gaolebber** [comment] 2022-03-08 04:42
@reevejd It has been solved perfectly. Thank you

**Closed** 2022-03-08 13:49 UTC
Labels: bug
